
import java.awt.Desktop;
import java.awt.event.KeyEvent;
import java.io.*;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class computer_accessories extends javax.swing.JFrame {

    private static final long serialVersionUID = 1L;

    /**
     * Creates new form computer_accessories
     */
    JFrame myFrame = new JFrame("Computer Accessories Store");
    
    public computer_accessories() {
        initComponents();
        setResizable(false);
        btnSave.setVisible(false);
        btnSaveAs.setText("Save");
        arrayProduct.add(new Product("P001","kingston","588","8 GB MicroSDHC","1 yr","storage devices"));
        arrayProduct.add(new Product("P002","remax","4000","wired stereo","3 yrs","headphones"));
        arrayProduct.add(new Product("P003","rapoo","1273","P00520HB wireless","3 yrs","headphones"));
        arrayProduct.add(new Product("P004","tenda","1125","150Mbps Nano","no","routers and networking"));
        arrayProduct.add(new Product("P005","asus geforce","8125","GT 710","5 yrs","graphic cards"));
        arrayProduct.add(new Product("P006","asus","13125","LCD Monitor","1 yr","monitors"));
        arrayProduct.add(new Product("P007","dell latitude","44500","i5 4GB","5 yrs","laptops"));
        arrayProduct.add(new Product("P008","ADD TEST","500","jst a test","1 yr","Graphic Cards"));
        arrayProduct.add(new Product("P008","iMice","1500","gaming","1 yr","mouses"));
        arrayProduct.add(new Product("P010","test","500","test","no","Graphic Cards"));
        arrayProduct.add(new Product("P011","HP","70000","i5 AMD","3 yr","laptops"));
        arrayProduct.add(new Product("P012","yasuds","450","16 GB","no","storage devices"));
        insertInTable(arrayProduct);
    }
    String file_name = "";
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jProgressBar1 = new javax.swing.JProgressBar();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        warranty1 = new javax.swing.JRadioButton();
        lblDescription = new javax.swing.JLabel();
        lblProduct_id = new javax.swing.JLabel();
        lblWarranty = new javax.swing.JLabel();
        warranty4 = new javax.swing.JRadioButton();
        txtDescription = new javax.swing.JTextField();
        warranty2 = new javax.swing.JRadioButton();
        warranty3 = new javax.swing.JRadioButton();
        lblPrice = new javax.swing.JLabel();
        txtProduct_id = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        cmbCategory = new javax.swing.JComboBox<>();
        lblCategory = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnClear = new javax.swing.JButton();
        btnAddProduct = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        btnSortByID = new javax.swing.JButton();
        btnSortByPrice = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnSaveAs = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblProduct_id1 = new javax.swing.JLabel();
        search_price = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblProduct_id2 = new javax.swing.JLabel();
        jCategoryAvaibale = new javax.swing.JComboBox<>();
        btnAvailable = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuNew = new javax.swing.JMenuItem();
        openMenuItem = new javax.swing.JMenuItem();
        jMenuExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuHelp = new javax.swing.JMenuItem();
        jMenuReport = new javax.swing.JMenuItem();

        jTextField2.setText("jTextField2");

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Computer Accessories Store");

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        buttonGroup1.add(warranty1);
        warranty1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        warranty1.setText("No");
        warranty1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                warranty1ActionPerformed(evt);
            }
        });

        lblDescription.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblDescription.setText("Description:");

        lblProduct_id.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblProduct_id.setText("Product_id:");

        lblWarranty.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblWarranty.setText("Warranty:");

        buttonGroup1.add(warranty4);
        warranty4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        warranty4.setText("5 yrs");

        txtDescription.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescriptionActionPerformed(evt);
            }
        });

        buttonGroup1.add(warranty2);
        warranty2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        warranty2.setText("1 yr");
        warranty2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                warranty2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(warranty3);
        warranty3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        warranty3.setText("3 yrs");

        lblPrice.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblPrice.setText("Price (Rs):");

        txtProduct_id.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtProduct_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProduct_idActionPerformed(evt);
            }
        });

        txtPrice.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPriceActionPerformed(evt);
            }
        });
        txtPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPriceKeyTyped(evt);
            }
        });

        txtName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        lblName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblName.setText("Name:");

        cmbCategory.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Categories", "Graphic Cards", "Laptops", "Routers and Networking", "Storage Devices", "Monitors", "Headphones", "Mouses" }));
        cmbCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCategoryActionPerformed(evt);
            }
        });

        lblCategory.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCategory.setText("Category:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("ADD Product to Store:");

        btnClear.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnAddProduct.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAddProduct.setText("Add Product");
        btnAddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProductActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(lblPrice))
                                    .addComponent(lblName, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtPrice)
                                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblProduct_id)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtProduct_id, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblDescription)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblCategory)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cmbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblWarranty)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(warranty1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(warranty2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(warranty3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(warranty4)))))
                        .addContainerGap(58, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnAddProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProduct_id)
                    .addComponent(txtProduct_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblWarranty)
                    .addComponent(warranty1)
                    .addComponent(warranty2)
                    .addComponent(warranty3)
                    .addComponent(warranty4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblCategory))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblName)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblDescription))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPrice)
                        .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product_id", "Category", "Company", "Warranty", "Price", "Description"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
        }

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Computer Accessories Details");
        jLabel5.setAlignmentX(2.0F);

        btnSortByID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSortByID.setText("Sort by Product ID");
        btnSortByID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortByIDActionPerformed(evt);
            }
        });

        btnSortByPrice.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSortByPrice.setText("Sort by Price");
        btnSortByPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortByPriceActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnSaveAs.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSaveAs.setText("Save As");
        btnSaveAs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveAsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(btnSortByID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSaveAs)
                .addGap(20, 20, 20))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(btnSortByPrice)
                    .addContainerGap(414, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSortByID)
                    .addComponent(btnSave)
                    .addComponent(btnSaveAs))
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(177, Short.MAX_VALUE)
                    .addComponent(btnSortByPrice)
                    .addContainerGap()))
        );

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Search Products");

        lblProduct_id1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblProduct_id1.setText("Search By Price (Rs):");

        search_price.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        search_price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_priceActionPerformed(evt);
            }
        });
        search_price.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                search_priceKeyTyped(evt);
            }
        });

        btnSearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSearch.setText("Search Accessories");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(lblProduct_id1))
                .addContainerGap(148, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSearch)
                    .addComponent(search_price, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblProduct_id1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(search_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearch)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Query Available Products");

        lblProduct_id2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblProduct_id2.setText("Product Available in category:");

        jCategoryAvaibale.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jCategoryAvaibale.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Categories", "Graphic Cards", "Laptops", "Routers and Networking", "Storage Devices", "Monitors", "Headphones", "Mouses" }));
        jCategoryAvaibale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCategoryAvaibaleActionPerformed(evt);
            }
        });

        btnAvailable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAvailable.setText("Accessories Available");
        btnAvailable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvailableActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(lblProduct_id2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAvailable)
                    .addComponent(jCategoryAvaibale, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblProduct_id2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCategoryAvaibale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAvailable)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Computer Accessories Store");
        jLabel6.setAlignmentX(1.0F);
        jLabel6.setAlignmentY(2.0F);
        jLabel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(0, 0, 0)));

        jMenu1.setText("File");

        jMenuNew.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuNew.setText("New File");
        jMenuNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuNewActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuNew);

        openMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        openMenuItem.setText("Open File");
        openMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(openMenuItem);

        jMenuExit.setText("Exit");
        jMenuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuExitActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");

        jMenuHelp.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        jMenuHelp.setText("General Help");
        jMenuHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuHelpActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuHelp);

        jMenuReport.setText("Read Report");
        jMenuReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuReportActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuReport);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtProduct_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProduct_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProduct_idActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void warranty2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_warranty2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_warranty2ActionPerformed

    private void txtDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescriptionActionPerformed

    private void txtPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPriceActionPerformed

    private void warranty1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_warranty1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_warranty1ActionPerformed

    private void cmbCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCategoryActionPerformed

    private void search_priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_priceActionPerformed

    private void jCategoryAvaibaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCategoryAvaibaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCategoryAvaibaleActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        txtProduct_id.setText("");
        txtName.setText("");
        txtPrice.setText("");
        txtDescription.setText("");
        buttonGroup1.clearSelection();
        cmbCategory.setSelectedIndex(0); 
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnAddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProductActionPerformed
        // TODO add your handling code here:
        String product_id = txtProduct_id.getText();
        String company = txtName.getText();
        String price = txtPrice.getText();
        String description = txtDescription.getText();
        String warranty = "";
        if(warranty1.isSelected()) {
            warranty = "no";
        } else if(warranty2.isSelected()){
            warranty = "1 yr";
        }
        else if(warranty3.isSelected()){
            warranty = "3 yrs";
        }
        else if(warranty4.isSelected()){
            warranty = "5 yrs";
        }
        
        String category = (String) cmbCategory.getSelectedItem();
        
        if ("".equals(warranty) || "".equals(price) || "".equals(product_id) || "".equals(company) || "".equals(description) || category.equals("Select Categories")){
            JOptionPane.showMessageDialog(myFrame, "please enter all the required information");
        } else {
            boolean already = false;
            for(int i =0; i<arrayProduct.size();i++){
                if (product_id.toLowerCase().equals(arrayProduct.get(i).product_id.toLowerCase())){
                    already = true;
                }
            }
            if(already == true){
                JOptionPane.showMessageDialog(myFrame, "The product ID you entered: "+product_id+" already exits.\nPlease try again with another product ID");
            }
            else{
                arrayProduct.add(new Product(product_id, company, price, description, warranty, category));
                clearTable();
                insertInTable(arrayProduct);
            }
            
        }         
    }//GEN-LAST:event_btnAddProductActionPerformed

    private void btnAvailableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvailableActionPerformed
        // TODO add your handling code here:
        String category = (String) jCategoryAvaibale.getSelectedItem();
        if (category.equals("Select Categories")){
            JOptionPane.showMessageDialog(myFrame, "please select the category");
        }
        else{
            String display = "";
            ArrayList<Product> found = new ArrayList<Product>();
            for (int i = 0; i < arrayProduct.size(); i++){
                if(category.toLowerCase().equals(arrayProduct.get(i).category.toLowerCase())){
                    found.add(arrayProduct.get(i));
                }
            }
            if(found.size()!=0){
                display= display+"There are " + found.size() + " product found in category: " + category + ": \n";
                for(int row = 0; row<found.size();row++){
                    display = display + (row+1)+ ") " + "\t Product_id: " + found.get(row).product_id + "\n";
                    display = display +  "\t Company: " + found.get(row).company + "\n";
                    display = display +  "\t Warranty: " + found.get(row).warranty + "\n";
                    display = display +  "\t Price: " + found.get(row).price + "\n";
                    display = display + "\t Description: " + found.get(row).description + "\n\n";                    
                }
                JOptionPane.showMessageDialog(myFrame,display); 
            }else{
                JOptionPane.showMessageDialog(myFrame,"There are no any product in category: "+category);
            }                  
        }
        
        
    }//GEN-LAST:event_btnAvailableActionPerformed

    
      
    private void jMenuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuExitActionPerformed

    private void openMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuItemActionPerformed
        // TODO add your handling code here:
        ArrayList<Product> temp = arrayProduct;
        try {
            arrayProduct.clear();
            file_name = JOptionPane.showInputDialog("Enter file company:");
            if (file_name.equals(null)){
                JOptionPane.showMessageDialog(myFrame, "please enter the file company");
            }
            else{                              
                File file=new File(file_name+".txt");    //creates a new file instance  
                FileReader fr=new FileReader(file);   //reads the file  
                BufferedReader br=new BufferedReader(fr);  //creates a buffering character input stream  
                String line;  
                
                clearTable();
                
                while((line=br.readLine())!=null)  
                {
                    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                    model.addRow(line.split(","));
                    jTable1.setModel(model);                
                }
                fr.close();
                
                for (int i = 0; i < jTable1.getRowCount(); i++){
                    arrayProduct.add(new Product(jTable1.getValueAt(i, 0).toString(),jTable1.getValueAt(i, 2).toString(),jTable1.getValueAt(i, 4).toString(),jTable1.getValueAt(i, 5).toString(),jTable1.getValueAt(i, 3).toString(),jTable1.getValueAt(i, 1).toString()));
                }
            }
            btnSaveAs.setText("Save As");
            btnSave.setVisible(true);

        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(myFrame, "The file name you entered does not exit");
        } catch (IOException ex) {
            Logger.getLogger(computer_accessories.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_openMenuItemActionPerformed

    private void insertInTable(ArrayList<Product> arrayProduct){
        for(int i=0; i<arrayProduct.size(); i++){
            Product obj = arrayProduct.get(i);
            Object[] row = new Object[]{obj.product_id, obj.category, obj.company, obj.warranty, obj.price, obj.description};
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.addRow(row);
            jTable1.setModel(model);
        }
    }
    
    private void clearTable(){
        for (int i = jTable1.getRowCount() - 1; i >= 0; i--) {
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.removeRow(i);
        }
    }
    
    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        sortByPrice();
        clearTable();
        insertInTable(arrayProduct);
        System.out.print(search_price.getText());
        if(!search_price.getText().equals("")){
            System.out.print("asdf");
            try{
                int price = Integer.parseInt(search_price.getText());
                System.out.print(price);
                
            
                boolean status = false;
                int lowest = 0;
                int highest = arrayProduct.size();
                int mid = (lowest+highest)/2;            
                boolean found = false;
                while (status == false){

                    System.out.print(lowest);
                    System.out.print(mid);
                    System.out.print(highest);
                    System.out.print("\n");
                    int priceCompare = Integer.parseInt(arrayProduct.get(mid).price);
                    if ( priceCompare == price){
                        status = true;
                        found = true;
                        while (mid !=0 && priceCompare == Integer.parseInt(arrayProduct.get(mid-1).price)){
                            System.out.print(mid);
                            mid = mid-1;
                        }
                        break;
                    }
                    else if (price > priceCompare){
                        lowest = mid + 1;
                    }
                    else{
                        highest = mid -1;
                    }
                    mid = (lowest+highest)/2;
                    if(lowest > highest+1 || highest < lowest || mid == arrayProduct.size()){
                        status = true; found=false;
                    }


                }
                if(found == true){
                    String dis = "Product ID: " + arrayProduct.get(mid).product_id + "\n Category: " + arrayProduct.get(mid).category + "\n Company: " + arrayProduct.get(mid).company + "\n Price(Rs)" + arrayProduct.get(mid).price; 
                    JOptionPane.showMessageDialog(myFrame, dis);
                }else{
                    JOptionPane.showMessageDialog(myFrame, "Product not found");
                }
                }
                catch(Exception e){
                    JOptionPane.showMessageDialog(myFrame,"The table is empty");
                }
        }else{
            JOptionPane.showMessageDialog(myFrame, "Enter the value of price to be searched");
        }
            
        
        
    }//GEN-LAST:event_btnSearchActionPerformed

    private void jMenuHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuHelpActionPerformed
        if (Desktop.isDesktopSupported()){
            try{
                Desktop.getDesktop().open(new File("src/files/help.txt"));
            } catch (IOException e){
                System.out.println(e);
            }
        }else{
            System.out.println("not supported");
        }
    }//GEN-LAST:event_jMenuHelpActionPerformed

    private void btnSortByIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortByIDActionPerformed
        // TODO add your handling code here:
        sortByProductID();
        clearTable();
        insertInTable(arrayProduct);
    }//GEN-LAST:event_btnSortByIDActionPerformed

    private void btnSortByPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortByPriceActionPerformed
        // TODO add your handling code here:
        sortByPrice();
        clearTable();
        insertInTable(arrayProduct);
    }//GEN-LAST:event_btnSortByPriceActionPerformed

    private void txtPriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPriceKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE))){
            evt.consume();
            JOptionPane.showMessageDialog(myFrame,"Please enter only Integer value");
        }
        
    }//GEN-LAST:event_txtPriceKeyTyped

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        if(jTable1.getRowCount()!=0){
            while(file_name.equals(null) || file_name.equals("")){
                file_name = JOptionPane.showInputDialog("Enter file name:");
                if(file_name.equals(null)){
                    file_name="";
                    break;
                }
                if(file_name.equals("")){JOptionPane.showMessageDialog(myFrame,"Please Enter the file name");}
            }
            System.out.print(file_name);
            if(file_name!=""){
                writeFile(arrayProduct, file_name);
                JOptionPane.showMessageDialog(myFrame,"Sucessfully Saved");
            } 
            
        }else{
            JOptionPane.showMessageDialog(myFrame,"Sorry!!! the table is empty");
        }
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void writeFile(ArrayList<Product> list, String file_name){        
        try {
            PrintWriter writer = null;
            writer = new PrintWriter(file_name+".txt", "UTF-8");
            ArrayList<String> row = new ArrayList<String>();
            for(int i = 0; i<list.size(); i++){
                row.add(list.get(i).product_id);
                row.add(list.get(i).category);
                row.add(list.get(i).company);
                row.add(list.get(i).warranty);
                row.add(list.get(i).price);
                row.add(list.get(i).description);
                writer.write(String.join(",", row)+"\n");
                row.clear();
            }
            writer.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(computer_accessories.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(computer_accessories.class.getName()).log(Level.SEVERE, null, ex);
        }
    }  
    
    private void btnSaveAsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveAsActionPerformed
        // TODO add your handling code here:
        if(jTable1.getRowCount()!= 0){
            int input=1;
            while (input == 1){
                file_name = JOptionPane.showInputDialog("Enter file company:");
                if(!file_name.equals("")){
                    File file=new File(file_name+".txt");
                    try { 
                        FileReader fr=new FileReader(file);
                        input = JOptionPane.showConfirmDialog(null, "This device already has a file named: "+file_name+"\nDo you wanna replace the file?");
                        if(input==1){JOptionPane.showMessageDialog(myFrame,"Please try again using next file name");}
                    } catch (FileNotFoundException ex) {
                        input = 0;
                    }
                }
                else{
                    JOptionPane.showMessageDialog(myFrame,"Please enter the file name");
                }

            }
            if (input == 0){
                writeFile(arrayProduct, file_name);
                JOptionPane.showMessageDialog(myFrame,"Sucessfully saved");
                btnSaveAs.setText("Save As");
                btnSave.setVisible(true);
            }
        }
        else{
            JOptionPane.showMessageDialog(myFrame,"Sorry!!! the table is empty");
        }
        
    }//GEN-LAST:event_btnSaveAsActionPerformed

    private void search_priceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_priceKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE))){
            evt.consume();
            JOptionPane.showMessageDialog(myFrame,"Please enter only Integer value");
        }
    }//GEN-LAST:event_search_priceKeyTyped

    private void jMenuNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuNewActionPerformed
        // TODO add your handling code here:
        clearTable();
        arrayProduct.clear();
        file_name="";
        btnSave.setVisible(false);
        btnSaveAs.setText("Save");
    }//GEN-LAST:event_jMenuNewActionPerformed

    private void jMenuReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuReportActionPerformed
        // TODO add your handling code here:
        if (Desktop.isDesktopSupported()){
            try{
                Desktop.getDesktop().open(new File("src/files/report.pdf"));
            } catch (IOException e){
                System.out.println(e);
            }
        }else{
            System.out.println("not supported");
        }
    }//GEN-LAST:event_jMenuReportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(computer_accessories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(computer_accessories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(computer_accessories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(computer_accessories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new computer_accessories().setVisible(true);
        });
    }

    
    private void sortByPrice(){
        for(int i = 0; i<arrayProduct.size()-1; i++){
            int minPosIndex = minimumPositionIndex(arrayProduct, i);
            Product temp = arrayProduct.get(minPosIndex);
            arrayProduct.set(minPosIndex, arrayProduct.get(i));
            arrayProduct.set(i, temp);
        }
    } 
    private void sortByProductID(){
        for(int i = 0; i<arrayProduct.size()-1; i++){
            int minPosIndex = minimumPositionID(arrayProduct, i);
            Product temp = arrayProduct.get(minPosIndex);
            arrayProduct.set(minPosIndex, arrayProduct.get(i));
            arrayProduct.set(i, temp);
        }
    } 
    private static int minimumPositionID(ArrayList<Product> list,int from){
        int minPosIndex = from;
        for(int i = from+1; i < list.size(); i++){
            if(list.get(i).product_id.compareTo(list.get(minPosIndex).product_id) < 0 ){
                minPosIndex = i;
            } 
        }
        return minPosIndex;
    }
    private static int minimumPositionIndex(ArrayList<Product> list,int from){
        int minPosIndex = from;
        for(int i = from+1; i < list.size(); i++){
            if(Integer.parseInt(list.get(i).price) < Integer.parseInt(list.get(minPosIndex).price) ){
                minPosIndex = i;
            }
        }
        return minPosIndex;
    }
   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddProduct;
    private javax.swing.JButton btnAvailable;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSaveAs;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSortByID;
    private javax.swing.JButton btnSortByPrice;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cmbCategory;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jCategoryAvaibale;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuExit;
    private javax.swing.JMenuItem jMenuHelp;
    private javax.swing.JMenuItem jMenuNew;
    private javax.swing.JMenuItem jMenuReport;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblProduct_id;
    private javax.swing.JLabel lblProduct_id1;
    private javax.swing.JLabel lblProduct_id2;
    private javax.swing.JLabel lblWarranty;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JTextField search_price;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtProduct_id;
    private javax.swing.JRadioButton warranty1;
    private javax.swing.JRadioButton warranty2;
    private javax.swing.JRadioButton warranty3;
    private javax.swing.JRadioButton warranty4;
    // End of variables declaration//GEN-END:variables
    ArrayList <Product> arrayProduct = new ArrayList<Product>();
    
}
